title: SociocaRtography
tagline: "R Machine Learning GIS"
theme: "08"
reverse: False
description: >
  Semantics and Syntaxes.

url: "http://parthkhare.github.io/"
author: "ramnathv.github.io"
  name: "Parth Khare"
  github: "parthkhare"
  format: "parthkhare"

sidebar:
  - {item: Urban Sciences, href: '/urban-sciences', icon: 'building-o'}
  - {item: Machine Learning, href: '/machine-learning', icon: 'cogs'}
  - {item: R-Utlity Kit, href: '/r-blog', icon: 'rocket'}
  - {item: Photography, href: 'https://parthkhare.format.com/', icon: 'camera-retro'}
  - {item: Blog, href: '/blog', icon: 'archive'}


projects:
  - {title: "Delhi Crime Voronoi", 
     url: "https://parthakhare.carto.com/viz/8c4d97e0-6510-11e6-ad84-0ef24382571b/embed_map/",
     thumbnail: 'dlcrdb.png'
    }
  - {title: "Delhi Crime Shiny",
     url: "https://sociocartography.shinyapps.io/DelhiCrime/",
     thumbnail: "dlcrsh.png"
    }
  - {title: India Crime NCRB,
  	 url: "https://sociocartography.shinyapps.io/SociocaRtography/",
  	 thumbnail: "incrsh.png"
  	}

blog
  - {title: R Utility Kit,
     url: "https://rutilitykit.wordpress.com/about/",
    }

presentation
  - {title: Decision Tree 101,
  	 url: 'http://www.slideshare.net/parthkhare/machine-learning-basics-trees-algrorithm-random-forest-gbm/',
    }
